### PR TITLE
Olaf's work on Auton

### PR DESCRIPTION
**Pull request by matthew-oberg**
All of the work done by @gretteoa today and little from yesterday. @gretteoa should be posting a summary of changes and work in discord this evening.

### CODE REVIEW

**Comment by caojohnny** [comment]
Is this working code?

**Comment by matthew-oberg** [comment]
We tested it, and it works. However all of it was done without your open PR being merged.

**Comment by matthew-oberg** [comment]
Should I merge yours or this one? @AgentTroll

**Comment by caojohnny** [comment]
Close mine. This PR already has my changes because I pulled from my own repo.

**Review by caojohnny — APPROVED** [review]

**Comment by matthew-oberg** [comment]
Great, thanks!

**Pull request merged**
